### PR TITLE
🚂 Begin supporting Rails 6.1

### PR DESCRIPTION
**Pull request by danott**
Publishing has been living on https://github.com/ministrycentered/premailer-rails/tree/greg/rails-6 since it's inception. Two years later, it seems like it may be worth getting the changes into the main branch of our fork?

### CODE REVIEW

**Comment by shanebonham** [comment]
People is actually using this branch: https://github.com/ministrycentered/premailer-rails/tree/v1.10.3-pco

I haven't looked into it too deeply, but I'm wondering if we should, after this, also merge in the upstream and cut our own `v{whatever.their.latest.tag.is}-pco`.

**Comment by danott** [comment]
I think that's a great idea. Closing the gap between our branch and the canonical gem feels like something future us will appreciate from current us.

**Comment by glosie** [comment]
I had long since forgotten about that branch 😅

**Comment by shanebonham** [comment]
Thinking further along those lines, is it weird that _we're_ locking down the max version of actionmailer when the upstream doesn't?

**Comment by shanebonham** [comment]
I also wonder if our original reason for needing a fork was resolved here: https://github.com/fphilipe/premailer-rails/pull/248

Still looking...

**Comment by shanebonham** [comment]
@danott Do you recall the original reason for forking, or more precisely, how to replicate the issue? It seems possible we may be able to drop the fork in favor of the upstream, but I'm not sure how to check.

**Comment by danott** [comment]
@shanebonham [v1.9.7/pco-communications-patch](https://github.com/fphilipe/premailer-rails/compare/master...ministrycentered:v1.9.7/pco-communication-patch) is the tag that Accounts continues to use to this day (on Rails 5). It looks like neither our [Rails 6](https://github.com/fphilipe/premailer-rails/compare/master...ministrycentered:greg/rails-6) nor our [Rails 6.1](https://github.com/fphilipe/premailer-rails/compare/master...ministrycentered:danott/rails-6-1) branches include that commit/change.

By the looks of those diffs, it seems like we may be able to get off of our fork, and back onto the upstream project on Rails 6.0 and 6.1. 🤔

**Comment by shanebonham** [comment]
@danott I want to say even the Rails 5.2 projects could update to the upstream if they wanted.

I didn't even realize Greg's branch wasn't based of our patch 🤔  I don't remember exactly, but I have a feeling that when [People updated to Rails 6](https://github.com/ministrycentered/people/commit/cdfc71921dcf2ea83b1e20ea81db3f8d4220229b), we created the [`v1.10.3-pco`](https://github.com/ministrycentered/premailer-rails/tree/v1.10.3-pco) tag, which was merely that patch commit on top of whatever the latest in the upstream was. By that time, they had removed the upper bound on `actionmailer`, so we didn't have to mess with the `gemspec` also.

**Comment by glosie** [comment]
> By that time, they had removed the upper bound on `actionmailer`, so we didn't have to mess with the `gemspec` also.

This sounds right to me too. Looking back through Calendar's history, it looks like we never even shipped my branch—we ended up upgrading from `v1.9.7/pco-communication-patch` to `v1.10.3-pco` with Rails 6.

**Comment by danott** [comment]
Great news everyone. I put Publishing onto the canonical `premailer-rails` gem, sent myself an email in Publishing's Rails console, and everything is working just fine. We do not need a fork in the Rails 6.0 and 6.1 world!

**Pull request closed without merging**
